### ISSUE TITLE
Create 2.8 version for Jackson 2.8

### ISSUE THREAD

**Issue by cowtowncoder** [michel-kraemer/bson4jackson#76]
I know that `bson4jackson` is quite compatible across multiple Jackson versions, but it would be nice to have a newer version that specifies Jackson 2.8.x dependencies, as users try to match minor versions (for good reason too, since not all Jackson components can retain cross-minor-version deps).
Doing this also allows bson module to implement latest hooks for low-level parser/generator.

**Comment by michel-kraemer** [comment]
Thanks for bringing this up. I'll keep you informed about the update.

**Comment by cowtowncoder** [comment]
@michel-kraemer No problem at all, thank you.

Actually, for full disclosure it's probably good to mention we just released 2.9.0 as well. :-)
So one possibility could be to focus on 2.9.0 instead, come to think of that, assuming bsonjackson 2.7.0 works fine with Jackson core, databind 2.8, which I believe is the case (I sort of test this via `jackson-benchmarks`).

**Comment by sepatel** [comment]
Issue #72 talks about the issues with the 2.7.0 version of bson4jackson. You really do need to release the 2.8.0 version as the lack of a release (despite multiple requests for this to happen) has already forced multiple different projects/people to fork this project for the sole purpose of creating a version of this code that is not snapshot that actually works.

**Comment by cfinckler** [comment]
Hi, are you still working on this? If so, it would be nice, to create a new version with the fixes in the current snapshot version. Thank you.

**Comment by michel-kraemer** [comment]
I'm currently on a longer vacation. I'll be able to release a new version by mid October. Sorry for the inconvenience.

**Comment by mattsdavis** [comment]
any update on a compatible version for Jackson 2.9.0? I'm currently getting an exception when using 2.9.0 
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.fixAccess()V

**Comment by zigzago** [comment]
@mattsdavis as a tmp workaround, this fork: https://mvnrepository.com/artifact/org.litote/bson4jackson-fork/2.8.0 is ok with jackson 2.9.2 (there is a bug in jackson 2.9.0)

HTH

**Comment by trumpetinc** [comment]
How's it looking for getting 2.9 released?

**Comment by michel-kraemer** [comment]
I just release bson4jackson 2.8.0. Sorry that it took me so long. Please note that version 2.9.0 will also be released later today or tomorrow.
